Feature/receiving post request
ONSdigital/dp-feedback-api pull request #14
Opened 2024-11-04 11:06 UTC by dhee-tree

### What

- Changed configs for sending email
- Upgraded dependencies, go version and linter
- Updated test format to match configs

### How to review

- CI test pass
- Sense check

### Who can review

!Me

2024-11-06 11:25 UTC, lindenmckenzie requested changes
Few little bits.

2024-11-06 11:25 UTC, lindenmckenzie commented on ci/component.yml
> +    tag: 1.23.1-bullseye
```suggestion
    tag: 1.23.2-bullseye
```

2024-11-06 11:25 UTC, lindenmckenzie commented on ci/component.yml
> +    tag: 1.23.1-bullseye
Same for others.

2024-11-06 11:25 UTC, lindenmckenzie commented on config/config.go
> +	MailPort     string `envconfig:"MAIL_PORT"`
Is this necessary? Was the linter complaining? Otherwise it's Mail.MailHost which seems a bit wordy.

2024-11-06 11:25 UTC, lindenmckenzie commented on features/feedback.feature
>          Description: very nice and useful website!
Do we have a test for the 'is general feedback: true' path?

2024-11-06 11:25 UTC, lindenmckenzie commented on go.mod
>  replace google.golang.org/grpc => google.golang.org/grpc v1.55.0
These replace statements should be removed as per our standard approach to dependency management.

2024-11-06 11:25 UTC, lindenmckenzie commented on main_test.go
>  	component.RegisterSteps(ctx)
Any reason this has been removed?

2024-11-06 14:33 UTC, lindenmckenzie reviewed
Some more minor comments.

2024-11-06 14:33 UTC, lindenmckenzie commented on api/feedback.go
> +		b.WriteString(fmt.Sprintf("Feedback Type: %s\n", mapper.ASpecificPage))
```suggestion
	if !*f.IsGeneralFeedback {
		b.WriteString(fmt.Sprintf("Feedback Type: %s\n", mapper.ASpecificPage))
```

2024-11-06 14:33 UTC, lindenmckenzie commented on api/feedback.go
> +		b.WriteString(fmt.Sprintf("Feedback Type: %s\n", mapper.ASpecificPage))
or you could even just provide the string based off that, saves a minor point of duplication.

2024-11-06 14:33 UTC, lindenmckenzie commented on api/feedback_test.go
>  Name: Mr Feedback reporter
we could expand the testing here to get both cases.

2024-11-06 16:17 UTC, dhee-tree commented on ci/component.yml
> +    tag: 1.23.1-bullseye
Done

2024-11-06 16:17 UTC, dhee-tree commented on config/config.go
> +	MailPort     string `envconfig:"MAIL_PORT"`
Done

2024-11-06 16:28 UTC, lindenmckenzie reviewed
Tiny comment to have a think about.

2024-11-06 16:28 UTC, lindenmckenzie commented on api/feedback_test.go
> +Page URL: https://testhost:1234/sub/path
Should we be printing the URL if it's general feedback? Maybe these should be mutually exclusive?

2024-11-07 09:04 UTC, dhee-tree commented on go.mod
>  replace google.golang.org/grpc => google.golang.org/grpc v1.55.0
Done

2024-11-07 12:53 UTC, lindenmckenzie approved these changes

2024-11-07 12:59 UTC, merged